name: Create, Build and Deploy into AKS Cluster

on: 
  push:
    branches: ['main']

env:
  AZURE_CONTAINER_REGISTRY: perfaidev.azurecr.io
  PROD_AZURE_CONTAINER_REGISTRY: perfaiprod.azurecr.io
  IMAGE_NAME: perfai-engine-testendpoints
  IMAGE_TAG: $(date "+%F-%H%M")
  RESOURCE_GROUP: Perfai-Dev
  CLUSTER_NAME: PerfAI-Dev
  PROD_RESOURCE_GROUP: Perfai-Prod
  PROD_CLUSTER_NAME: PerfAI-Prod

  
####### DEVELOPER ENV #######
jobs:
  Deploy-Developer:
#    needs: Deploy-Prod-Replica
    runs-on: ubuntu-latest
#    runs-on: azure-self-hosted
      
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    # Step 1: Checkout Code
    - name: Checkout code
      uses: actions/checkout@v4

   # Step 2: Login to Azure
    - name: Azure Login
      uses: Azure/login@v2.2.0
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        # client-id: # optional
        # tenant-id: # optional
        # subscription-id: # optional
        # enable-AzPSSession: # optional
        # environment: # optional, default is azurecloud

    # Step 3: Login to Azure Container Registry (ACR)
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
         username: ${{ secrets.DEV_ACR_USERNAME }}
         password: ${{ secrets.DEV_ACR_PASSWORD }}
         login-server: perfaidev.azurecr.io
       
    - name: 'Setting Image date-tag'
      run: |-
           image_tag=$IMAGE_TAG
           echo $image_tag
      
    - name: Get Current Date
      id: date
      run: echo "::set-output name=date::$(date '+%F-%H%M')"

    # Step 4: Build Docker Image
    - name: Build Docker image
      run: |
        docker build -t perfaidev.azurecr.io/perfai-engine-testendpoints:${{ github.sha }}  -f ./docker/Dockerfile .
        docker tag perfaidev.azurecr.io/perfai-engine-testendpoints:${{ github.sha }} perfaidev.azurecr.io/perfai-engine-testendpoints:${{ steps.date.outputs.date }}
        docker push perfaidev.azurecr.io/perfai-engine-testendpoints:${{ steps.date.outputs.date }}
         
    # Step 6: Set up Kubectl
    - name: Set up Kubectl
      uses: Azure/setup-kubectl@v4.0.0
      with:
        version: 'latest'

     # Step 7: Get AKS credentials      
    - name: Get AKS Credentials
      run: |
        az aks get-credentials --resource-group ${{ env.RESOURCE_GROUP }} --name ${{ env.CLUSTER_NAME }} --overwrite-existing

    - name: Update Deployment with New Image
      run: |
        kubectl set image deployment/perfai-engine-testendpoints perfai-engine-testendpoints=${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.date.outputs.date }} -n perfai
      
    - name: Verify Deployment Rollout
      run: |
        kubectl rollout status deployment/perfai-engine-testendpoints -n perfai
        
    - name: Check Running Pods
      run: |
        kubectl get pods -n perfai | grep perfai-engine-testendpoints


### Email Alert Notification ###
    - name: Send mail
      if: failure()
      uses: dawidd6/action-send-mail@v3.9.0
      with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "🚨 Build Failure: ${{ github.repository }} #${{ github.run_number }} 🚨"
          body: |
             Hi Team,

             Unfortunately, the build for the project **${{ github.repository }}** has failed. Below are the details:

             **Build Information:**
               - Repository:  ${{ github.repository }}
               - Branch:  ${{ github.ref_name }}
               - Commit SHA:  ${{ github.sha }}
               - Commit Message:  ${{ github.event.head_commit.message }}
               - Triggered By: ${{ github.actor }}

             **Failure Summary:*
               - Please review the logs for more details: [View Logs] 
                   ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          to: yahyashareef@perfai.ai        
          from: PerfAI          
       
